<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '将AI 接入VR',
    'style' => '',
    'thumb' => 'http://www.phpcms.com/uploadfile/2019/0704/20190704094344174.jpg',
    'keywords' => 'vr',
    'description' => 'ObEN成立于 2014 年，成立之初曾募集到 15 万美元的种子轮融资，入围过 HTC Vive X 孵化器。2016年11月曾获得770万美元A论融资，领投方是中国盾安集团旗下投资分部 CrestValue Capital，参投方包括知名',
    'posids' => '1',
    'url' => 'http://www.phpcms.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1562247551',
    'updatetime' => '1562486193',
    'hitsid' => 'c-1-1',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '我的世界',
    'style' => '',
    'thumb' => 'http://www.phpcms.com/uploadfile/2019/0707/20190707035534982.jpg',
    'keywords' => '世界',
    'description' => '没有我的啊山东黄金爱仕达阿三哥啊是的噶圣诞节航速的',
    'posids' => '0',
    'url' => 'http://www.phpcms.com/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1562486067',
    'updatetime' => '1562486199',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>