<?php exit;?>07-04 20:36:04 | 2 | array_keys() expects parameter 1 to be array, boolean given | phpcms\libs\functions\global.func.php | 1500
<?php exit;?>07-04 20:36:04 | 2 | in_array() expects parameter 2 to be array, null given | phpcms\libs\functions\global.func.php | 1501
<?php exit;?>07-04 20:37:11 | 2 | fsockopen(): php_network_getaddresses: getaddrinfo failed: ��֪������������  | phpcms\libs\classes\http.class.php | 84
<?php exit;?>07-04 20:37:11 | 2 | fsockopen(): unable to connect to juhe.phpcms.cn:80 (php_network_getaddresses: getaddrinfo failed: ��֪������������ ) | phpcms\libs\classes\http.class.php | 84
<?php exit;?>07-04 20:39:53 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:39:53 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:39:53 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:39:53 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:39:53 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:39:58 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:39:58 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:39:58 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:39:58 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:39:58 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:41:40 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:41:40 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:41:40 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:41:40 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:41:40 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:42:00 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:42:00 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:42:00 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:42:00 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:42:00 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:42:06 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:42:06 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:42:06 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:42:06 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:42:06 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:47:08 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:47:08 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:47:08 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:47:08 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:47:08 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:49:34 | 2 | fsockopen(): php_network_getaddresses: getaddrinfo failed: ��֪������������  | phpcms\libs\classes\http.class.php | 84
<?php exit;?>07-04 20:49:34 | 2 | fsockopen(): unable to connect to juhe.phpcms.cn:80 (php_network_getaddresses: getaddrinfo failed: ��֪������������ ) | phpcms\libs\classes\http.class.php | 84
<?php exit;?>07-04 20:50:05 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:05 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:05 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:50:05 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:50:05 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:50:20 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:20 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:20 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:50:20 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:50:20 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:50:30 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:30 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:30 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:50:30 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:50:30 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:50:48 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:48 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step.inc.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 12
<?php exit;?>07-04 20:50:48 | 2 | file_get_contents(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/license.txt): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 28
<?php exit;?>07-04 20:50:48 | 2 | include(D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php): failed to open stream: No such file or directory | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 20:50:48 | 2 | include(): Failed opening 'D:\phpStudy\PHPTutorial\WWW\phpcms\phpcms\..\install/step/step1.tpl.php' for inclusion (include_path='.;C:\php\pear') | D:\phpStudy\PHPTutorial\WWW\phpcms\install\install.php | 30
<?php exit;?>07-04 21:24:43 | 2 | fsockopen(): php_network_getaddresses: getaddrinfo failed: ��֪������������  | phpcms\libs\classes\http.class.php | 84
<?php exit;?>07-04 21:24:43 | 2 | fsockopen(): unable to connect to juhe.phpcms.cn:80 (php_network_getaddresses: getaddrinfo failed: ��֪������������ ) | phpcms\libs\classes\http.class.php | 84
<?php exit;?>07-04 21:40:15 | 2 | fsockopen(): unable to connect to tool.phpcms.cn:80 (������ӷ���һ��ʱ���û���ȷ�𸴻�ӵ����û�з�Ӧ�����ӳ���ʧ�ܡ�
) | phpcms\libs\classes\http.class.php | 84
